---
- name: run docker
  hosts: webservers
  connection: local
  tasks:
     - name: Run docker container
       command: docker run -d --name hello-container --mount source=data,target=/scripts hello:word
